---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible yamllint
  - ansible --version

  # Install serverspec
  - ruby -v
  - gem install serverspec

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Run yamllint checking for linting issues in all yml files
  - yamllint .

  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local"

  # Run the role/playbook again, checking to make sure it's idempotent.
  # Allowing 1 change that is just reading state for this role
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local
    | grep -q 'changed=1.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Run serverpec tests
  - rake spec

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
